#!/bin/bash -ex
install()
{
    apt-get update
    DEBIAN_FRONTEND=noninteractive apt-get -y \
        -o DPkg::Options::=--force-confdef \
        -o DPkg::Options::=--force-confold \
        install $@
}

# Add NGINX proxy header field
CONF=/etc/nginx/proxy_params
sed -i "s|proxy_add_x_forwarded_for;|proxy_add_x_forwarded_for;\nproxy_set_header X-Forwarded-Proto \$scheme;\nproxy_set_header X-NginX-Proxy true;|" $CONF

# create cache directories
mkdir -p /var/lib/nginx/cache/tmp
chown -R www-data:root /var/lib/nginx/cache
chmod -R 700 /var/lib/nginx/cache
